### ISSUE TITLE
am married to frog but no honeymoon optioon

### ISSUE THREAD

**Issue by ParaSwarm** [MrOnosa/solo-dev-game-jam-4#1]
married frog, but cannot experience joy of matrimony, no honeymoon, kids (tadpole)?  ?????? bug??? please fix coding

**Comment by ParaSwarm** [comment]
maybe allow for fiance first, maybe shoot engagement ring before final power up to diamond

**Comment by ParaSwarm** [comment]
I am on coding asignment

will create boolean for honeymoons = true or false, engagementring = true or false or null, diamondengagementring = true or false or NULL!!

I will have an update for u forthwith. need to install visual code studio on debian system LOL, pain in my rears!!

**Comment by ParaSwarm** [comment]
@MrOnosa can u rteview my coding, it builds and runs but does not compile?? pls help

**Comment by MrOnosa** [comment]
@ParaSwarm, thank you for hopping into this. Let's not croak over small bugs—just do what the compiler toad you. Don't let errors bog you down.

**Comment by ParaSwarm** [comment]
thx you!! @mranosa also I see u put frog jokes in there LOL!!! i am hopping laughing HARD!!!! 

pls reopen ticket issue

**Comment by ParaSwarm** [comment]
@misteronosa i am confused lol, pls incorporate my codechang
