### ISSUE TITLE
interested in building an ML agent (Not exactly an issue)

### ISSUE THREAD

**Issue by Mohit-Pala** [MrOnosa/solo-dev-game-jam-4#2]
Hey, i found your game on itch.io. 

I am interested in building a Reinforcement Learning agent for your game as a part of my capstone project. 
I am still looking at various open source projects but i liked your game the most so far.
Just wanted to reach out and see if you were cool with your game being controlled by Ai and whatnot

**Comment by MrOnosa** [comment]
Thank you for asking. Yes, go ahead. I hope you can share the results with me, but you're under no obligation to. I look forward to seeing a bot get the secret ending. 🐸

**Comment by Mohit-Pala** [comment]
Appreciate it, my capstone starts next semester so ill update you then.
